data_preproces:
  type: nn
  data_process_params:
    data_filename: data/train/yndx_20150901_20200901.csv
    value_column: OPEN
    date_column: TRADEDATE
    # value_column: open
    # date_column: begin
    sequence_length: 10
    scaler_type: std
    diff_data: first_diff
train_val_test_split:
  type: nn
  train_val_test_split_params:
    val_part: 0.2
    test_part: 0.05
model:
  type: xlstm
  model_params:
    input_features: 1
    output_features: 1
    xlstm_config:
      mlstm_block:
        mlstm:
          conv1d_kernel_size: 4
          qkv_proj_blocksize: 4
          num_heads: 4
      slstm_block:
        slstm:
          backend: cuda # or vanilla
          num_heads: 4
          conv1d_kernel_size: 4
          bias_init: powerlaw_blockdependent
        feedforward:
          proj_factor: 1.1
          act_fn: gelu
      context_length: 10
      num_blocks: 3
      embedding_dim: 32
      add_post_blocks_norm: False
      dropout: 0.3
      slstm_at:
        - 1  #[1] # for [] it also works, so if no sLSTM is in the stack
train:
  criterion: MSE
  num_epochs: 500
  shuffle_data: True
  batch_size: 32
  val_batch_size: 32
  optimizer:
    type: AdamW
    optimizer_params:
      lr: 0.006
  scheduler:
    type: LinearWarmupCosineAnnealing
    scheduler_params:
      warmup_steps: 50
      decay_until_step: 500
      max_lr: 0.006
      min_lr: 0.0006
test:
  output_filename: xlstm_predict.csv
  criterion: MAE
  criterion_top_k:
    - 1
    - 7
    - 14
    - 28